# Generated by Django 4.2.4 on 2023-08-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_blogsite_author_alter_blogsite_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsite',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
