# Generated by Django 4.2.4 on 2023-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blogsite_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsite',
            name='theme',
            field=models.TextField(default='Enter the theme of the Blog in 100 words', max_length=100),
        ),
    ]
